# Generated by Django 6.1 on 2026-09-26 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('modulo_principal', models.CharField(blank=True, max_length=80, verbose_name='módulo principal')),
            ],
            options={
                'verbose_name': 'cargo',
                'verbose_name_plural': 'cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Delegacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='dirección')),
                ('comuna', models.CharField(default='La Serena', max_length=80)),
            ],
            options={
                'verbose_name': 'delegación municipal',
                'verbose_name_plural': 'delegaciones municipales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='SIGED-SGR Delegaciones La Serena', max_length=120)),
                ('comuna', models.CharField(default='La Serena', max_length=80)),
                ('region', models.CharField(default='Región de Coquimbo', max_length=80, verbose_name='región')),
                ('sla_verde_max_dias', models.PositiveSmallIntegerField(default=3, verbose_name='SLA verde (máx. días)')),
                ('sla_amarillo_max_dias', models.PositiveSmallIntegerField(default=5, verbose_name='SLA amarillo (máx. días)')),
                ('meta_tubo_porcentaje', models.PositiveSmallIntegerField(default=80, verbose_name='meta tubo (%)')),
                ('encuesta_habilitada', models.BooleanField(default=True)),
                ('max_atenciones_mismo_usuario', models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                'verbose_name': 'parámetro del sistema',
                'verbose_name_plural': 'parámetros del sistema',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text='Clave usada por el sistema (ej: administrador).', max_length=30, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: FUN-001', max_length=20, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_ultimo_ingreso', models.DateField(blank=True, null=True, verbose_name='fecha último ingreso')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='cuentas.cargo')),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='cuentas.delegacion', verbose_name='delegación')),
            ],
            options={
                'verbose_name': 'funcionario',
                'verbose_name_plural': 'funcionarios',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Ej: USR-001', max_length=20, null=True, unique=True, verbose_name='código')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='nombre de usuario')),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='cuentas.cargo')),
                ('delegacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='cuentas.delegacion', verbose_name='delegación')),
                ('funcionario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='cuentas.funcionario')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='cuentas.rol')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuario Django')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['nombre'],
            },
        ),
    ]
