# Generated by Django 6.1 on 2026-10-04 20:30

from pathlib import Path

import django.db.models.deletion
from django.db import migrations, models


def _ddl_v019() -> str:
    """El CREATE TABLE de V019, sin el encabezado. En MySQL se ejecuta tal cual."""
    ruta = Path(__file__).resolve().parents[2] / "sql" / "migraciones" / "V019__codigo_un_uso.sql"
    texto = ruta.read_text(encoding="utf-8")
    return texto[texto.index("CREATE TABLE") :]


class CreateCodigoUnUso(migrations.CreateModel):
    """En MySQL crea la tabla con el DDL de V019. SQLite usa el esquema del ORM para la suite."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "mysql":
            schema_editor.execute(_ddl_v019())
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        schema_editor.execute("DROP TABLE codigo_un_uso")


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_rut_obligatorio'),
    ]

    operations = [
        CreateCodigoUnUso(
            name='CodigoUnUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposito', models.CharField(max_length=20)),
                ('cuenta_vecino_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('codigo_hash', models.CharField(max_length=64)),
                ('canal', models.CharField(default='CORREO', max_length=10)),
                ('destino_mascara', models.CharField(blank=True, max_length=80, null=True)),
                ('expira_en', models.DateTimeField()),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos_un_uso', to='cuentas.usuario')),
            ],
            options={
                'verbose_name': 'código de un solo uso',
                'verbose_name_plural': 'códigos de un solo uso',
                'db_table': 'codigo_un_uso',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['usuario', 'proposito', 'creado_en'], name='idx_codigo_dueno'), models.Index(fields=['cuenta_vecino_id', 'proposito', 'creado_en'], name='idx_codigo_vecino'), models.Index(fields=['expira_en'], name='idx_codigo_expira')],
                'constraints': [models.CheckConstraint(condition=models.Q(('intentos__lte', 5)), name='ck_codigo_intentos'), models.CheckConstraint(condition=models.Q(('proposito__in', ['RECUPERAR_CLAVE', 'MFA_EMAIL', 'LOGIN_VECINO', 'VERIFICAR_CORREO'])), name='ck_codigo_proposito'), models.CheckConstraint(condition=models.Q(('canal__in', ['CORREO', 'SMS'])), name='ck_codigo_canal')],
            },
        ),
    ]
