# Generated by Django 6.1 on 2026-10-04 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_rut_obligatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hash', models.CharField(max_length=128, verbose_name='hash del código')),
                ('expira', models.DateTimeField()),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('usado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='codigos_recuperacion', to='cuentas.usuario')),
            ],
            options={
                'verbose_name': 'código de recuperación',
                'verbose_name_plural': 'códigos de recuperación',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['usuario', 'usado'], name='idx_recup_usuario_usado')],
            },
        ),
    ]
