# Generated by Django 6.1 on 2026-09-26 01:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        ('requerimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'meta',
                'verbose_name_plural': 'metas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: NTF-001', max_length=20, unique=True, verbose_name='código')),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('aviso', 'Aviso'), ('agenda', 'Agenda')], default='info', max_length=10)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('enlace', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: TUB-001', max_length=20, unique=True, verbose_name='código')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripción')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_compromiso', models.DateField()),
                ('estado', models.CharField(choices=[('INGRESADO', 'Ingresado'), ('PENDIENTE', 'Pendiente'), ('EN PROCESO', 'En proceso'), ('REALIZADO', 'Realizado')], default='INGRESADO', max_length=12)),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to='cuentas.delegacion', verbose_name='delegación')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to='cuentas.funcionario')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to='requerimientos.vecino')),
            ],
            options={
                'verbose_name': 'compromiso (tubo de trabajo)',
                'verbose_name_plural': 'compromisos (tubo de trabajo)',
                'ordering': ['fecha_compromiso', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: AG-001', max_length=20, unique=True, verbose_name='código')),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('tipo', models.CharField(max_length=60)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(blank=True, max_length=150)),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='cuentas.delegacion', verbose_name='delegación')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='cuentas.funcionario')),
            ],
            options={
                'verbose_name': 'evento de agenda',
                'verbose_name_plural': 'agenda',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=80, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(verbose_name='fecha término')),
                ('dias_totales', models.PositiveSmallIntegerField(default=90)),
                ('meta_cumplimiento_tubo', models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='meta cumplimiento tubo (%)')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('delegacion_piloto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mediciones', to='cuentas.delegacion', verbose_name='delegación piloto')),
            ],
            options={
                'verbose_name': 'periodo de medición',
                'verbose_name_plural': 'periodos de medición',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: ACT-001', max_length=20, unique=True, verbose_name='código')),
                ('fecha_actividad', models.DateField(default=django.utils.timezone.localdate)),
                ('contacto', models.CharField(blank=True, max_length=150)),
                ('servicio', models.CharField(max_length=200)),
                ('codigo_verificador', models.CharField(blank=True, max_length=60, verbose_name='código verificador')),
                ('imagen_verificadora', models.CharField(blank=True, max_length=200, verbose_name='verificador (imagen/documento)')),
                ('punto_validado', models.BooleanField(default=False)),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='cuentas.delegacion', verbose_name='delegación')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='cuentas.funcionario')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='control_gestion.meta', verbose_name='ítem / meta')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'ordering': ['-fecha_actividad', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ItemFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponderador', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='ponderador (%)')),
                ('meta_trimestre', models.PositiveIntegerField(verbose_name='meta del trimestre')),
                ('avance_actual', models.PositiveIntegerField(default=0)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cuentas.funcionario')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_funcionario', to='control_gestion.meta')),
            ],
            options={
                'verbose_name': 'ítem de la matriz SGR',
                'verbose_name_plural': 'ítems de la matriz SGR',
                'ordering': ['funcionario__codigo', '-ponderador'],
                'constraints': [models.UniqueConstraint(fields=('funcionario', 'meta'), name='uniq_item_funcionario_meta')],
            },
        ),
    ]
