# Generated by Django 6.1 on 2026-09-26 01:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'canal de ingreso',
                'verbose_name_plural': 'canales de ingreso',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'tipo de atención',
                'verbose_name_plural': 'tipos de atención',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'tipo de gestión',
                'verbose_name_plural': 'tipos de gestión',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AreaSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: AREA-001', max_length=20, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('encargado_nombre', models.CharField(blank=True, help_text='Texto libre si el encargado no es funcionario registrado.', max_length=120, verbose_name='nombre encargado')),
                ('tiempo_promedio_dias', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='tiempo promedio (días)')),
                ('total_casos_mes', models.PositiveIntegerField(default=0)),
                ('porcentaje_cumplimiento', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='% cumplimiento')),
                ('satisfaccion_promedio', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('icono', models.CharField(blank=True, help_text='Clase Bootstrap Icons, ej: bi-people-fill', max_length=60)),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_a_cargo', to='cuentas.funcionario')),
            ],
            options={
                'verbose_name': 'área de soporte',
                'verbose_name_plural': 'áreas de soporte',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SubAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('tipo_atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_atenciones', to='requerimientos.tipoatencion', verbose_name='tipo de atención')),
            ],
            options={
                'verbose_name': 'sub atención',
                'verbose_name_plural': 'sub atenciones',
                'ordering': ['tipo_atencion__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('rut', models.CharField(blank=True, help_text='Formato 12.345.678-9. Vacío si no se registró.', max_length=12, null=True, unique=True, verbose_name='RUT')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('territorio', models.CharField(blank=True, help_text='Sector (Centro, Norte, Sur...)', max_length=60)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('delegacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vecinos', to='cuentas.delegacion', verbose_name='delegación')),
                ('tipo_gestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vecinos', to='requerimientos.tipogestion', verbose_name='tipo de gestión')),
            ],
            options={
                'verbose_name': 'vecino',
                'verbose_name_plural': 'vecinos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: TK-1001', max_length=20, unique=True, verbose_name='ticket')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.localdate)),
                ('asignado_a', models.CharField(blank=True, help_text='Cuadrilla o equipo asignado tal como se registró.', max_length=120, verbose_name='asignado a (texto)')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Cuello Botella Central', 'Cuello Botella Central'), ('Resuelto', 'Resuelto')], default='Pendiente', max_length=30)),
                ('evaluacion_satisfaccion', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='evaluación (1-5)')),
                ('comentario_satisfaccion', models.TextField(blank=True, verbose_name='comentario satisfacción')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos', to='requerimientos.areasoporte', verbose_name='área temática')),
                ('canal_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos', to='requerimientos.canalingreso', verbose_name='canal de ingreso')),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos', to='cuentas.delegacion', verbose_name='delegación')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos', to='cuentas.funcionario', verbose_name='funcionario asignado')),
                ('tipo_gestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos', to='requerimientos.tipogestion', verbose_name='tipo de entrada')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos', to='requerimientos.vecino')),
            ],
            options={
                'verbose_name': 'requerimiento',
                'verbose_name_plural': 'requerimientos',
                'ordering': ['-fecha_ingreso', '-codigo'],
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('cerrada', 'Cerrada')], default='pendiente', max_length=12)),
                ('observacion', models.TextField(blank=True, verbose_name='observación')),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='cuentas.delegacion', verbose_name='delegación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='cuentas.usuario', verbose_name='registrada por')),
                ('sub_atencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='requerimientos.subatencion', verbose_name='sub atención')),
                ('tipo_atencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='requerimientos.tipoatencion', verbose_name='tipo de atención')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='requerimientos.vecino')),
            ],
            options={
                'verbose_name': 'atención',
                'verbose_name_plural': 'atenciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='subatencion',
            constraint=models.UniqueConstraint(fields=('tipo_atencion', 'nombre'), name='uniq_subatencion_por_tipo'),
        ),
    ]
